# Generated by Django 5.2 on 2026-04-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('hr_name', models.CharField(blank=True, max_length=150, null=True)),
                ('applied', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
