# Generated by Django 5.2 on 2026-04-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('not_applied', 'Not Applied'), ('applied', 'Applied'), ('interview', 'Interview'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='not_applied', max_length=20),
        ),
    ]
